### ISSUE TITLE
libxdg-basedir src/basedir.c memset() emulation fatally broken

### ISSUE THREAD

**Issue by andim2** [devnev/libxdg-basedir#1]
Hi,
# else

static void xdgZeroMemory(void\* p, int n)
{
while (n > 0) { ((char*)p)[n] = 0; ++n; }
}
# endif

'nuff said ;)

**Comment by devnev** [comment]
Wow... I don't even... blarg?

**Comment by tweerwag** [comment]
Just look at the code more carefully. It clears memory until n wraps around and becomes negative... You probably want something like

``` c
static void xdgZeroMemory(void* p, int n)
{
    for (; n > 0; n--)
        ((char*)p)[n] = 0;
}
```

**Comment by ILMostro** [comment]
I doubt this is legit; i.e. not what people expect to be like the libxdg-basedir from n.ethz.ch... Though, I wish it was

**Comment by tweerwag** [comment]
Huh? What are you referring to with _this_? This issue? My suggestion? This whole repository?

**Comment by davmac314** [comment]
@tweerwag your suggested fix is incorrect. Consider the simple case of `xdgZeroMemory(p, 1)` - it should only set `p[0] = 0`, instead it will set `p[1] = 0` (and will not set `p[0] = 0`). I have a correct fix in my fork.

**Comment by tweerwag** [comment]
Oops... Good to hear someone is picking up maintaining!

**Comment by ILMostro** [comment]
Yeah, sorry for the noise there.  IIRC, I had been trying to find a recent version of the codebase and wasn't sure if this repo was dead, active, separate from the original...  Thank you
