### ISSUE TITLE
What is xdgHandle and how should I use it?

### ISSUE THREAD

**Issue by ponzipoh** [devnev/libxdg-basedir#4]
Looking at [basedir.h](https://github.com/devnev/libxdg-basedir/blob/master/include/basedir.h), xdgHandle is an argument to all functions, even to _xdgInitHandle_.
What's the purpose of this handle and how am I supposed to use it?

**Comment by s4msung** [comment]
Have a look at the Tests!

**Comment by devnev** [comment]
It is optional everywhere, in that NULL can be passed instead (not documented, sorry). As mentioned above, see tests for how to use. The choice of interface is questionable but that was over 10 years ago :)
