### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by yshui** [devnev/libxdg-basedir#8]
The last release was 6 years ago, and there has since been important fixes applied to the codebase.

Could you make a new release?

**Comment by davmac314** [comment]
@yshui I have forked this project and will do basic maintenance until/unless the original author takes up the reigns again. I have issued a new release. https://github.com/davmac314/libxdg-basedir

**Comment by mid-kid** [comment]
It seems the original author merged the patches a couple of years ago, yet didn't make a new release... What are distros supposed to use @devnev?

**Comment by devnev** [comment]
I've bumped the patch version (mainly to avoid any confusion, not because anything has changed since the 1.2.2 release by @davmac314) and tagged a release.

**Comment by mid-kid** [comment]
Thanks!
